# Generated by Django 5.2.8 on 2026-01-15 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'Company address', 'verbose_name_plural': 'Company addresses'},
        ),
        migrations.AddField(
            model_name='company',
            name='on_site_url',
            field=models.URLField(blank=True, help_text='Ссылка на страницу компании в каталоге/рейтинге', verbose_name='Есть на сайте'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Призначена країна для користувача', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.country'),
        ),
    ]
